AWSTemplateFormatVersion: "2010-09-09"
Description: >

  New Relic ECS integration.

  - Creates a secret that stores your license key.
  - Creates a managed policy that grants access to the license key.
  - Creates an instance role to be used for the task ExecutionRole.

Resources:
  NewRelicLicenseKeySecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: "New Relic license key."
      SecretString: !Ref LicenseKey

  

Parameters:
  LicenseKey:
    Type: String
    Description: "New Relic license key. (From the New Relic menu bar, select Account settings.)"

Outputs:
 
  LicenseKeySecretARN:
    Description: "ARN of the license key secret for which the ExecutionRole has read access"
    Value: !Ref NewRelicLicenseKeySecret
